# A simple 404 page
error_404:
  enable: true
  subtitle: "页面没有找到"
  background: 

menu:
  # 首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  分类: /categories/ || fas fa-folder-open
  标签: /tags/ || fas fa-tags
  # List||fas fa-list:
  #   - Music || /music/ || fas fa-music
  #   - Movie || /movies/ || fas fa-video
  # 友链: /link/ || fas fa-link
  关于: /about/ || fas fa-heart

highlight_theme: mac light
highlight_copy: true

# 主页 top_img 样式
index_top_img_height: 400px

social:
  fab fa-github: https://github.com/xiefenga || Github
  fas fa-envelope: mailto:x1294699027@gmail.com || Email
  fas fa-check-double: https://juejin.cn/user/2990289124862462 || 掘金
  fas fa-rss: /fff

# 文章meta
post_meta:
  page:
    date_type: both # created or updated or both 主页文章日期是创建日或者更新日或都显示
    date_format: relative # date/relative 显示日期还是相对日期
    categories: true # true or false 主页是否显示分类
    tags: true # true or false 主页是否显示标籤
    label: true # true or false 显示描述性文字
  post:
    date_type: both # created or updated or both 文章页日期是创建日或者更新日或都显示
    date_format: relative # date/relative 显示日期还是相对日期
    categories: true # true or false 文章页是否显示分类
    tags: true # true or false 文章页是否显示标籤
    label: true # true or false 显示描述性文字

post_edit:
  enable: false
  # url: https://github.com/user-name/repo-name/edit/branch-name/subdirectory-name/
  # For example: https://github.com/jerryc127/butterfly.js.org/edit/main/source/
  url: /404.html

# post_pagination (文章上下页按钮)
# value: 1 || 2 || false
# 1: The 'next post' will link to old post
# 2: The 'next post' will link to new post
# false: disable pagination
# post_pagination: false


# 文章中图片的描述 [xxxx]
photofigcaption: true


# index_post_content:
#   method: 3
#   length: 500 # if you set method to 2 or 3, the length need to config


disable_top_img: false
# index_img:	 false      #主页的 top_img
default_top_img:  /custom_assets/img/index_top.jpg	        #默认的 top_img，当页面的 top_img 没有配置时，会显示 default_top_img
 # archive_img:	        #归档页面的 top_img
 # tag_img:	        #tag        #子页面 的 默认 top_img
 # category_img:	        #category 子页面 的 默认 top_img
tag_per_img:	       #tag 子页面的 top_img，可配置每个 tag 的 top_img
  JavaScript: http://oss.xiefeng.tech/img/20210303201508.jpg
  React: http://oss.xiefeng.tech/img/20210303202309.png
  Vue: http://oss.xiefeng.tech/img/20210315221604.png

category_per_img:    #category 子页面的 top_img，可配置每个 category 的 top_img
  JavaScript: http://oss.xiefeng.tech/img/20210303201508.jpg
  React: http://oss.xiefeng.tech/img/20210303202309.png
  Vue: http://oss.xiefeng.tech/img/20210315221604.png

# 文章末尾添加版权信息
post_copyright:
  enable: true
  decode: true
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# copy settings
# copyright: Add the copyright information after copied content (复製的内容后面加上版权信息)
copy:
  enable: true
  copyright:
    enable: true
    limit_count: 50
  

# 阅读模式
readmode: true

# 改变字体
change_font_size: true


mermaid:
  enable: true
  # built-in themes: default/forest/dark/neutral
  theme: default

default_cover:
  - https://cdn.jsdelivr.net/gh/jerryc127/CDN@latest/cover/default_bg.png
  - https://cdn.jsdelivr.net/gh/jerryc127/CDN@latest/cover/default_bg2.png
  - https://cdn.jsdelivr.net/gh/jerryc127/CDN@latest/cover/default_bg3.png

# anchor
# when you scroll in post , the url will update according to header id.
anchor: true

# fancybox http://fancyapps.com/fancybox/3/
fancybox: true

# 美化页面显示
beautify:
  enable: true
  field: site # site/post
  title-prefix-icon: '\f0c1'
  title-prefix-icon-color: "#F47466"

# 分享
addThis:
  enable: false
  pubid:

# Share.js
# https://github.com/overtrue/share.js
sharejs:
  enable: false
  sites: facebook,twitter,wechat,weibo,qq

# AddToAny
# https://www.addtoany.com/
addtoany:
  enable: false
  item: facebook,twitter,wechat,sina_weibo,facebook_messenger,email,copy_link

toc:
  enable: true
  number: true
  style_simple: false

# 数学公式
katex:
  enable: true
  # true 表示每一页都加载katex.js
  # false 需要时加载，须在使用的Markdown Front-matter 加上 katex: true
  per_page: false
  hide_scrollbar: true

# mathjax:
#   enable: true
#   # true 表示每一頁都加載mathjax.js
#   # false 需要時加載，須在使用的Markdown Front-matter 加上 mathjax: true
#   per_page: false

# 点击特效
fireworks:
  enable: true
  zIndex: 9999 # -1 or 9999
  mobile: false

# 头像
avatar:
  img: /custom_assets/img/avatar.jpg
  effect: false # 头像会一直转圈

# 黑暗模式
darkmode:
  enable: true
  # dark mode和 light mode切换按钮
  button: true
  autoChangeMode: false

# 博客字体
# Font settings for the site title and site subtitle
# 左上角网站名字 主页居中网站名字
# blog_title_font:
  # font_link: https://fonts.googleapis.com/css?family=Titillium+Web&display=swap
  # font-family: Titillium Web, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft JhengHei', 'Microsoft YaHei', sans-serif

# 本地搜索
local_search:
  enable: true

# 网站副标题
subtitle:
  enable: true
  # 打字效果
  effect: true
  # 循环或者只打字一次
  loop: true
  # source调用第三方服务
  # source: false 关闭调用
  # source: 1  调用搏天api的随机语录（简体） 
  # source: 2  调用一言网的一句话（简体） 
  # source: 3  调用一句网（简体） 
  # source: 4  调用今日诗词（简体
  # subtitle 会先显示 source , 再显示 sub 的内容
  source: 4
  # 如果有英文逗号' , ',请使用转义字元 &#44;
  # 如果有英文双引号' " ',请使用转义字元 &quot;
  # 开头不允许转义字元，如需要，请把整个句子用双引号包住
  # 例如 ”&quotNever put off till tomorrow what you can do today&quot"
  # 如果关闭打字效果，subtitle只会显示sub的第一行文字
  sub:
    - 今日事&#44;今日毕
    - Never put off till tomorrow what you can do today

# 页面加载动画
preloader: false

# 网页footer
footer:
  owner:
    enable: true
    since: 2020
  custom_text: <a href="https://beian.miit.gov.cn/" rel="external nofollow noopener noreferrer" target="_blank">苏ICP备 2020051656号 </a>

footer_bg: true

# 鼠标悬停65ms，预加载
instantpage: true

# 当用户点击链接，通过ajax更新页面需要变化的部分，然后使用HTML5的pushState修改浏览器的URL地址。
# 这样可以不用重复加载相同的资源（css/js）， 从而提升网页的加载速度。
pjax: 
  enable: true
  exclude:
    - /music/
    - /no-pjax/


# 添加额外的js/css/meta等
inject:
  head:
  	- <link rel="stylesheet" href="/custom_assets/css/custom.css">
  bottom:
  	- <script src="/custom_assets/js/console.js"></script>

# 字数统计
wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

# 网站图标
favicon: /custom_assets/img/avatar.jpg

# 侧边栏
aside:
  enable: true
  hide: false
  button: true  # 侧边栏可以被按钮关闭
  mobile: false # 手机页面（ 显示宽度 < 768px ）是否显示aside内容
  position: right # left or right
  card_author:
    enable: true
    description:
    button:
      enable: false
	    icon: fab fa-github
      text: fellow me
      link: https://github.com/xiefenga
  card_announcement:
    enable: false
    content: This is my Blog
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
  card_categories:
    enable: true
    limit: 0 # if set 0 will show all
    expand: false # none/true/false
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: true
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
  card_webinfo:
    enable: false
    post_count: true
    last_push_date: true

# 评论
comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo
  use:
    # - Valine
    # - Twikoo
  text: true # Display the comment name next to the button
  lazyload: true
  count: false # Display comment count in top_img
  card_post_count: false # Display comment count in Home Page

# Valine 评论设置
valine:
  appId:  # leancloud application app id
  appKey:  # leancloud application app key
  pageSize: 10 # comment list page size
  avatar: monsterid # gravatar style https://valine.js.org/#/avatar
  lang: zh-CN # i18n: zh-CN/zh-TW/en/ja
  placeholder: 记得留下你的暱称和邮箱....可以快速收到回復 # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail,link #valine comment header info (nick/mail/link)
  recordIP: false # Record reviewer IP
  serverURLs: # This configuration is suitable for domestic custom domain name users, overseas version will be automatically detected (no need to manually fill in)
  bg: /img/comment_bg.png # valine background
  emojiCDN: # emoji CDN
  enableQQ: false # enable the Nickname box to automatically get QQ Nickname and QQ Avatar
  requiredFields: nick,mail # required fields (nick/mail)
  option:

# twikoo 评论设置
twikoo:
  envId:
  region:
  option:






# Google Webmaster tools verification.
# See: https://www.google.com/webmasters
google_site_verification: true

# Bing Webmaster tools verification.
# See: https://www.bing.com/webmaster
bing_site_verification:

# Yandex Webmaster tools verification.
# See: https://webmaster.yandex.ru
yandex_site_verification:

# 百度站长验证
# Baidu Webmaster tools verification.
# See: https://ziyuan.baidu.com/site
baidu_site_verification: true